version: v1

labels:
  - prefix: kind
    multiple: false
    list: [ "feature", "fix", "chore", "docs", "refactor" ]
    needs:
      comment: |
        @$AUTHOR: There are no 'kind' label on this PR. You need a 'kind' label to generate the release note automatically.

        * `/kind feature`
        * `/kind fix`
        * `/kind chore`
        * `/kind docs`
        * `/kind refactor`

  - prefix: priority
    multiple: false
    list: [ "urgent-now", "important-soon" ]

chat-ops:
  - cmd: /close
    type: close

  - cmd: /cc
    type: none # does not trigger anything

  - cmd: "/request (@.+)+"
    type: review

  - cmd: "/retest oss/governance"
    type: dispatch
    dispatch: "OSS/Governance"
