version: v1

labels:
  - label: "kind/chore"
    matcher:
      title: "^chore:.*"

checks:
  - context: "Release Drafter"
    url: "https://github.com/fuxingloh/vue-horizontal/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for release drafting.
    labels:
      any: [ "kind/feature", "kind/fix", "kind/chore", "kind/docs", "kind/refactor" ]
