name: 'OSS Governance Bot'
description: 'Speed up issue triaging with automated chat-bot and chat-ops operations with quality control hierarchy'
author: 'BirthdayResearch'
branding:
  icon: zap
  color: white

inputs:
  config-path:
    description: 'The path for the governance configuration'
    default: '.github/governance.yml'
    required: false
  github-token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT) for everything else'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'dist/index.js'
