name: 'OSS Governance'
description: 'Collection of documentations and tool to bring efficacy to your open source software project governance.'
author: 'Fuxing Loh'
branding:
  icon: zap
  color: white

inputs:
  config-path:
    description: 'The path for the governance configuration'
    default: '.github/governance.yml'
    required: false
  github-token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT) for everything else'
    required: false
    default: ${{ github.token }}
  comment-token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT) to post comment as a user'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'dist/index.js'
