name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run pack

      - uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9
        with:
          message: 'Diff from format, lint and pack'

  lint_prettier:
    name: "Lint (prettier)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npx --no-install prettier --check **/*.ts

  lint_eslint:
    name: "Lint (eslint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npx --no-install eslint src/**/*.ts

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run test:coverage
