name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run pack

      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          message: 'Diff from format, lint and pack'

  lint_prettier:
    name: "Lint (prettier)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npx --no-install prettier --check **/*.ts

  lint_eslint:
    name: "Lint (eslint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npx --no-install eslint src/**/*.ts

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run test:coverage
