name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run pack

      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          message: 'Diff from format, lint and pack'

  lint_prettier:
    name: "Lint (prettier)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npx --no-install prettier --check **/*.ts

  lint_eslint:
    name: "Lint (eslint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npx --no-install eslint src/**/*.ts

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run test:coverage
