name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - run: npm ci
      - run: npm run build
      - run: npm run format
      - run: npm run lint
      - run: npm run pack
      - run: npm run test:coverage

      - uses: EndBug/add-and-commit@998652d28d7702d095d40f52ae42982a80ae8c7d
        with:
          message: 'Diff from format, lint and pack'
