name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run pack

      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          message: 'Diff from format, lint and pack'

  lint_prettier:
    name: "Lint (prettier)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npx --no-install prettier --check **/*.ts

  lint_eslint:
    name: "Lint (eslint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npx --no-install eslint src/**/*.ts

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run test:coverage
