name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@df69d584deac33d8569990cb6413f82447181076
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
