name: Release Tags

on:
  release:
    types: [ released ]

jobs:
  release-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: vweevers/additional-tags-action@f54689cf358d5368ed738306a414a3b020957296
