name: Release Tags

on:
  release:
    types: [ released ]

jobs:
  release-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: vweevers/additional-tags-action@f54689cf358d5368ed738306a414a3b020957296
