name: Release Tags

on:
  release:
    types: [ released ]

jobs:
  release-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - uses: vweevers/additional-tags-action@f54689cf358d5368ed738306a414a3b020957296
