name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - path/to/manifest/labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
