name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: micnncim/action-label-syncer@0e9c5104859d0e78219af63791636eba42382b5d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
